<a href="https://colab.research.google.com/github/Naman09746/Learning/blob/main/Deep-Learning-For-Computer-Vision/Tensor%26Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [3]:
tensor_zero_d=tf.constant(10)
print(tensor_zero_d)

tf.Tensor(10, shape=(), dtype=int32)


In [20]:
tensor_one_d=tf.constant([1,2,3,4])#dtype int
print(tensor_one_d)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [25]:
# tensor_one_d=tf.constant([1,2,3,4.])#dtype float32
# print(tensor_one_d)
tensor_one_d_f=tf.constant([1,2,3,4],dtype=tf.float32)#dtype float32
print(tensor_one_d)

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float32)


In [26]:
#CASTING
casted_tensor_one_d= tf.cast(tensor_one_d_f,dtype=tf.int32)
print(casted_tensor_one_d)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [9]:
tensor_two_d=tf.constant([
     [1,2,3],
     [4,5,6]
    ])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [13]:
tensor_three_d=tf.constant([
    [
        [1,2,3],
        [5,6,7]
    ],
    [
        [0,9,8],
        [7,6,5]
    ]
])
print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [5 6 7]]

 [[0 9 8]
  [7 6 5]]], shape=(2, 2, 3), dtype=int32)


In [17]:
tensor_four_d=tf.constant([
    [
        [
            [1,2,3,4],
            [5,6,7,8]
        ],
        [
            [1,2,3,4],
            [5,6,7,8]
        ]
    ]
])
print(tensor_four_d)

tf.Tensor(
[[[[1 2 3 4]
   [5 6 7 8]]

  [[1 2 3 4]
   [5 6 7 8]]]], shape=(1, 2, 2, 4), dtype=int32)


In [27]:
import numpy as np

In [28]:
np_array= np.array([1,2,3])
print(np_array)

[1 2 3]


In [29]:
converted_tensor=tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [8]:
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=3,
    batch_shape=[2],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float32)


In [5]:
fill_tensor=tf.fill(
    [2,3],
    9
)
print(fill_tensor)

tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)


In [3]:
ones_tensor=tf.ones(
    [2,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [9]:
ones_like_tensor=tf.ones_like(
    eye_tensor
)
print(ones_like_tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 3, 3), dtype=float32)
