<a href="https://colab.research.google.com/github/Naman09746/Learning/blob/main/Deep-Learning-For-Computer-Vision/Tensor%26Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf

In [3]:
tensor_zero_d=tf.constant(10)
print(tensor_zero_d)

tf.Tensor(10, shape=(), dtype=int32)


In [4]:
tensor_one_d=tf.constant([1,2,3,4])#dtype int
print(tensor_one_d)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [5]:
# tensor_one_d=tf.constant([1,2,3,4.])#dtype float32
# print(tensor_one_d)
tensor_one_d_f=tf.constant([1,2,3,4],dtype=tf.float32)#dtype float32
print(tensor_one_d)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [6]:
#CASTING
casted_tensor_one_d= tf.cast(tensor_one_d_f,dtype=tf.int32)
print(casted_tensor_one_d)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [7]:
tensor_two_d=tf.constant([
     [1,2,3],
     [4,5,6]
    ])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [8]:
tensor_three_d=tf.constant([
    [
        [1,2,3],
        [5,6,7]
    ],
    [
        [0,9,8],
        [7,6,5]
    ]
])
print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [5 6 7]]

 [[0 9 8]
  [7 6 5]]], shape=(2, 2, 3), dtype=int32)


In [9]:
tensor_four_d=tf.constant([
    [
        [
            [1,2,3,4],
            [5,6,7,8]
        ],
        [
            [1,2,3,4],
            [5,6,7,8]
        ]
    ]
])
print(tensor_four_d)

tf.Tensor(
[[[[1 2 3 4]
   [5 6 7 8]]

  [[1 2 3 4]
   [5 6 7 8]]]], shape=(1, 2, 2, 4), dtype=int32)


In [10]:
import numpy as np

In [11]:
np_array= np.array([1,2,3])
print(np_array)

[1 2 3]


In [12]:
converted_tensor=tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [13]:
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=3,
    batch_shape=[2],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float32)


In [14]:
fill_tensor=tf.fill(
    [2,3],
    9
)
print(fill_tensor)

tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)


In [15]:
ones_tensor=tf.ones(
    [2,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [16]:
ones_like_tensor=tf.ones_like(
    eye_tensor
)
print(ones_like_tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 3, 3), dtype=float32)


In [17]:
zeros_tensor=tf.zeros(
    [2,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(zeros_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [18]:
zeros_like_tensor=tf.zeros_like(
    eye_tensor
)
print(zeros_like_tensor)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 3, 3), dtype=float32)


In [19]:
print(tensor_three_d.shape)

(2, 2, 3)


In [20]:
tf.rank(tensor_three_d)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [21]:
tf.size(tensor_three_d)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [22]:
tf.size(tensor_three_d,out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

In [23]:
random_tensor= tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 99.346275 100.7396  ]
 [100.05765  100.62559 ]
 [100.5143    99.63983 ]], shape=(3, 2), dtype=float32)


In [24]:
uniform_tensor= tf.random.uniform(
    [3,2],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(uniform_tensor)

tf.Tensor(
[[0.77173483 0.28625965]
 [0.40544045 0.11925483]
 [0.46497262 0.7783743 ]], shape=(3, 2), dtype=float32)


In [25]:
tf.random.set_seed(5)
print(tf.random.uniform([1],seed=1))
print(tf.random.uniform([1],seed=1))
print(tf.random.uniform([1],seed=1))

tf.Tensor([0.3875184], shape=(1,), dtype=float32)
tf.Tensor([0.98592305], shape=(1,), dtype=float32)
tf.Tensor([0.9647], shape=(1,), dtype=float32)


In [30]:
tensor_indexed= tf.constant([1,2,3,4,5,6,7])
print(tensor_indexed)
print(tensor_indexed[0:3])#min:max-1
print(tensor_indexed[0:6:2])

tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 3 5], shape=(3,), dtype=int32)


In [31]:
tensor_2_d=tf.constant([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(tensor_2_d)
print(tensor_2_d[0:2,1:3])

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)


In [32]:
print(tensor_2_d[...,1:3])

tf.Tensor(
[[ 2  3]
 [ 6  7]
 [10 11]], shape=(3, 2), dtype=int32)


In [33]:
x_abs=tf.constant([-2,-1,0,1,2])
print(tf.abs(x_abs))

tf.Tensor([2 1 0 1 2], shape=(5,), dtype=int32)


In [35]:
tf.abs(tf.constant([-2,-1,0,1,2]))

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 1, 0, 1, 2], dtype=int32)>

In [36]:
x_abs_complex=tf.constant([-2-4j,1+1j,-5+7j,0])
print(tf.abs(x_abs_complex))

tf.Tensor([4.47213595 1.41421356 8.60232527 0.        ], shape=(4,), dtype=float64)


In [37]:
tf.sqrt(2.25**2+ 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949020385742>

In [39]:
x_1=tf.constant([1,2,3,4])
x_2=tf.constant([5,6,7,8])
print(tf.add(x_1,x_2))
print(tf.subtract(x_1,x_2))
print(tf.multiply(x_1,x_2))
print(tf.divide(x_1,x_2))

tf.Tensor([ 6  8 10 12], shape=(4,), dtype=int32)
tf.Tensor([-4 -4 -4 -4], shape=(4,), dtype=int32)
tf.Tensor([ 5 12 21 32], shape=(4,), dtype=int32)
tf.Tensor([0.2        0.33333333 0.42857143 0.5       ], shape=(4,), dtype=float64)


In [42]:
# x3=tf.constant([7],dtype=tf.float32)
# print(tf.math.multiply(x_1,x3))
x3=tf.constant([7],dtype=tf.int32) # Change the data type of x3 to int32 to match x_1
print(tf.math.add(x_1,x3))

tf.Tensor([ 8  9 10 11], shape=(4,), dtype=int32)


In [ ]:
x_argmax=