<a href="https://colab.research.google.com/github/Naman09746/Learning/blob/main/Deep-Learning-For-Computer-Vision/Tensor%26Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [2]:
tensor_zero_d=tf.constant(10)
print(tensor_zero_d)

tf.Tensor(10, shape=(), dtype=int32)


In [3]:
tensor_one_d=tf.constant([1,2,3,4])#dtype int
print(tensor_one_d)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [4]:
# tensor_one_d=tf.constant([1,2,3,4.])#dtype float32
# print(tensor_one_d)
tensor_one_d_f=tf.constant([1,2,3,4],dtype=tf.float32)#dtype float32
print(tensor_one_d)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [5]:
#CASTING
casted_tensor_one_d= tf.cast(tensor_one_d_f,dtype=tf.int32)
print(casted_tensor_one_d)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [6]:
tensor_two_d=tf.constant([
     [1,2,3],
     [4,5,6]
    ])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [7]:
tensor_three_d=tf.constant([
    [
        [1,2,3],
        [5,6,7]
    ],
    [
        [0,9,8],
        [7,6,5]
    ]
])
print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [5 6 7]]

 [[0 9 8]
  [7 6 5]]], shape=(2, 2, 3), dtype=int32)


In [8]:
tensor_four_d=tf.constant([
    [
        [
            [1,2,3,4],
            [5,6,7,8]
        ],
        [
            [1,2,3,4],
            [5,6,7,8]
        ]
    ]
])
print(tensor_four_d)

tf.Tensor(
[[[[1 2 3 4]
   [5 6 7 8]]

  [[1 2 3 4]
   [5 6 7 8]]]], shape=(1, 2, 2, 4), dtype=int32)


In [9]:
import numpy as np

In [10]:
np_array= np.array([1,2,3])
print(np_array)

[1 2 3]


In [11]:
converted_tensor=tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [12]:
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=3,
    batch_shape=[2],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float32)


In [13]:
fill_tensor=tf.fill(
    [2,3],
    9
)
print(fill_tensor)

tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)


In [14]:
ones_tensor=tf.ones(
    [2,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [15]:
ones_like_tensor=tf.ones_like(
    eye_tensor
)
print(ones_like_tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 3, 3), dtype=float32)


In [16]:
zeros_tensor=tf.zeros(
    [2,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(zeros_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [17]:
zeros_like_tensor=tf.zeros_like(
    eye_tensor
)
print(zeros_like_tensor)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 3, 3), dtype=float32)


In [18]:
print(tensor_three_d.shape)

(2, 2, 3)


In [19]:
tf.rank(tensor_three_d)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [20]:
tf.size(tensor_three_d)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [21]:
tf.size(tensor_three_d,out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

In [22]:
random_tensor= tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 99.72055   97.86284 ]
 [100.52519   99.7028  ]
 [ 99.76009   99.127266]], shape=(3, 2), dtype=float32)


In [23]:
uniform_tensor= tf.random.uniform(
    [3,2],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(uniform_tensor)

tf.Tensor(
[[0.28773892 0.36275947]
 [0.34678805 0.47150123]
 [0.848035   0.85248005]], shape=(3, 2), dtype=float32)


In [24]:
tf.random.set_seed(5)
print(tf.random.uniform([1],seed=1))
print(tf.random.uniform([1],seed=1))
print(tf.random.uniform([1],seed=1))

tf.Tensor([0.3875184], shape=(1,), dtype=float32)
tf.Tensor([0.98592305], shape=(1,), dtype=float32)
tf.Tensor([0.9647], shape=(1,), dtype=float32)


In [25]:
tensor_indexed= tf.constant([1,2,3,4,5,6,7])
print(tensor_indexed)
print(tensor_indexed[0:3])#min:max-1
print(tensor_indexed[0:6:2])

tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 3 5], shape=(3,), dtype=int32)


In [26]:
tensor_2_d=tf.constant([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
print(tensor_2_d)
print(tensor_2_d[0:2,1:3])

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)
tf.Tensor(
[[2 3]
 [6 7]], shape=(2, 2), dtype=int32)


In [27]:
print(tensor_2_d[...,1:3])

tf.Tensor(
[[ 2  3]
 [ 6  7]
 [10 11]], shape=(3, 2), dtype=int32)


In [28]:
x_abs=tf.constant([-2,-1,0,1,2])
print(tf.abs(x_abs))

tf.Tensor([2 1 0 1 2], shape=(5,), dtype=int32)


In [29]:
tf.abs(tf.constant([-2,-1,0,1,2]))

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([2, 1, 0, 1, 2], dtype=int32)>

In [30]:
x_abs_complex=tf.constant([-2-4j,1+1j,-5+7j,0])
print(tf.abs(x_abs_complex))

tf.Tensor([4.47213595 1.41421356 8.60232527 0.        ], shape=(4,), dtype=float64)


In [31]:
tf.sqrt(2.25**2+ 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949020385742>

In [32]:
x_1=tf.constant([1,2,3,4])
x_2=tf.constant([5,6,7,8])
print(tf.add(x_1,x_2))
print(tf.subtract(x_1,x_2))
print(tf.multiply(x_1,x_2))
print(tf.divide(x_1,x_2))

tf.Tensor([ 6  8 10 12], shape=(4,), dtype=int32)
tf.Tensor([-4 -4 -4 -4], shape=(4,), dtype=int32)
tf.Tensor([ 5 12 21 32], shape=(4,), dtype=int32)
tf.Tensor([0.2        0.33333333 0.42857143 0.5       ], shape=(4,), dtype=float64)


In [33]:
# x3=tf.constant([7],dtype=tf.float32)
# print(tf.math.multiply(x_1,x3))
x3=tf.constant([7],dtype=tf.int32) # Change the data type of x3 to int32 to match x_1
print(tf.math.add(x_1,x3))

tf.Tensor([ 8  9 10 11], shape=(4,), dtype=int32)


In [34]:
x_argmax=tf.constant(([2,23,42,41,4],
                      [3,4,6,16,64],
                      [13,54,44,34,4]))
print(x_argmax)

tf.Tensor(
[[ 2 23 42 41  4]
 [ 3  4  6 16 64]
 [13 54 44 34  4]], shape=(3, 5), dtype=int32)


In [35]:
print(tf.math.argmax(x_argmax))

tf.Tensor([2 2 2 0 1], shape=(5,), dtype=int64)


In [36]:
x=tf.constant([[2,3],[3,4]])
y=tf.constant([[3,4],[5,6]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[   8,   81],
       [ 243, 4096]], dtype=int32)>

In [37]:
tf.pow(tf.constant(2),tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [38]:
tf.math.reduce_sum(
    input_tensor=tensor_two_d,
    axis=None,
    keepdims=False,
    name=None
)

<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [39]:
tf.math.top_k(tensor_two_d,k=1)

TopKV2(values=<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[3],
       [6]], dtype=int32)>, indices=<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[2],
       [2]], dtype=int32)>)

In [40]:
x_1=tf.constant([[1,2,3],
                [4,5,6]])
x_2=tf.constant([[5,6,7,8],
                 [1,3,5,6],
                 [3,4,1,2]]) # Added a row to x_2 to make it compatible for matrix multiplication

print(x_1.shape)
print(x_2.shape)

tf.linalg.matmul(
    x_1,x_2,transpose_a=False,transpose_b=False,adjoint_a=False,adjoint_b=False,a_is_sparse=False,b_is_sparse=False,
    output_type=None,
    name=None
)

(2, 3)
(3, 4)


<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[16, 24, 20, 26],
       [43, 63, 59, 74]], dtype=int32)>

In [41]:
tf.transpose(x_1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [42]:
tensor_two_d=tf.constant([
    [1,2,3],
    [4,5,6]
    ])
print(tensor_two_d)

tensor_out_d=tf.constant([[1,0,0],
                          [0,0,0]])
print(tensor_out_d)

tf.linalg.band_part(tensor_two_d,num_lower=0,num_upper=1)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 0],
       [0, 5, 6]], dtype=int32)>

In [43]:
tensor_two_d = tf.constant([
    [1, 2],
    [4, 5]
], dtype=tf.float32)  # Changed the shape to (2, 2) to make it square
print(tensor_two_d)

tensor_two_d_inv=tf.linalg.inv(tensor_two_d)

tf.Tensor(
[[1. 2.]
 [4. 5.]], shape=(2, 2), dtype=float32)


In [44]:
tensor_two_d@tensor_two_d_inv

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.]], dtype=float32)>

In [45]:
s,u,v=tf.linalg.svd(tensor_two_d)
print(s)
print(u)
print(v)

tf.Tensor([6.767828  0.4432736], shape=(2,), dtype=float32)
tf.Tensor(
[[ 0.3245364  -0.94587314]
 [ 0.94587314  0.3245364 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.6069936   0.79470664]
 [ 0.79470664 -0.6069936 ]], shape=(2, 2), dtype=float32)


In [46]:
import numpy as np

In [47]:
A=np.array([[2,3,4,5],
            [3,4,5,6],
            [5,6,7,8]])
B=np.array([[2,3,4,5],
            [3,4,5,6],
            [5,6,7,8],
            [1,2,3,4]])
print(A.shape)
print(B.shape)

(3, 4)
(4, 4)


In [48]:
print(np.matmul(A,B))

[[ 38  52  66  80]
 [ 49  67  85 103]
 [ 71  97 123 149]]


In [49]:
print("Einsum C:")
print(np.einsum("ij,jk-> ik",A,B))

Einsum C:
[[ 38  52  66  80]
 [ 49  67  85 103]
 [ 71  97 123 149]]


In [50]:
A=np.array([[2,3,4,5],
            [3,4,5,6],
            [5,6,7,8]])
B=np.array([[2,3,4,5],
            [3,4,5,6],
            [5,6,7,8]])
print(A.shape)
print(B.shape)
print("Haramond C=:")
print(A*B)

(3, 4)
(3, 4)
Haramond C=:
[[ 4  9 16 25]
 [ 9 16 25 36]
 [25 36 49 64]]


In [51]:
print("Transposed A:")
print(A.T)

print("Einsum Transpose")
print(np.einsum("ij->ji",A))

Transposed A:
[[2 3 5]
 [3 4 6]
 [4 5 7]
 [5 6 8]]
Einsum Transpose
[[2 3 5]
 [3 4 6]
 [4 5 7]
 [5 6 8]]


In [52]:
batchsize = 32
s_q = 64
s_k=128
s_v=64
modelsize = 512

In [53]:
Q=batchsize,s_q,modelsize
K=batchsize,s_k,modelsize
V=batchsize,s_v,modelsize

In [54]:
Q=np.random.randn(32,64,512)
K=np.random.randn(32,128,512)
V=np.random.randn(32,128,64)

In [55]:
np.einsum()

ValueError: must specify the einstein sum subscripts string and at least one operand, or at least one operand and its corresponding subscripts list

In [56]:
tensor_three_d.shape

TensorShape([2, 2, 3])

In [59]:
x_expanded= tf.expand_dims(tensor_three_d,axis=0)
print(x_expanded)

tf.Tensor(
[[[[1 2 3]
   [5 6 7]]

  [[0 9 8]
   [7 6 5]]]], shape=(1, 2, 2, 3), dtype=int32)


In [65]:
x_squeezed= tf.squeeze(x_expanded,axis=0)
print(x_squeezed)

tf.Tensor(
[[[1 2 3]
  [5 6 7]]

 [[0 9 8]
  [7 6 5]]], shape=(2, 2, 3), dtype=int32)


In [67]:
x_reshape= tf.reshape(x_expanded,[2,3,2])
print(x_reshape)

tf.Tensor(
[[[1 2]
  [3 5]
  [6 7]]

 [[0 9]
  [8 7]
  [6 5]]], shape=(2, 3, 2), dtype=int32)
