<a href="https://colab.research.google.com/github/Naman09746/Learning/blob/main/Deep-Learning-For-Computer-Vision/Tensor%26Variables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import tensorflow as tf

In [14]:
tensor_zero_d=tf.constant(10)
print(tensor_zero_d)

tf.Tensor(10, shape=(), dtype=int32)


In [15]:
tensor_one_d=tf.constant([1,2,3,4])#dtype int
print(tensor_one_d)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [16]:
# tensor_one_d=tf.constant([1,2,3,4.])#dtype float32
# print(tensor_one_d)
tensor_one_d_f=tf.constant([1,2,3,4],dtype=tf.float32)#dtype float32
print(tensor_one_d)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [17]:
#CASTING
casted_tensor_one_d= tf.cast(tensor_one_d_f,dtype=tf.int32)
print(casted_tensor_one_d)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [18]:
tensor_two_d=tf.constant([
     [1,2,3],
     [4,5,6]
    ])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [19]:
tensor_three_d=tf.constant([
    [
        [1,2,3],
        [5,6,7]
    ],
    [
        [0,9,8],
        [7,6,5]
    ]
])
print(tensor_three_d)

tf.Tensor(
[[[1 2 3]
  [5 6 7]]

 [[0 9 8]
  [7 6 5]]], shape=(2, 2, 3), dtype=int32)


In [20]:
tensor_four_d=tf.constant([
    [
        [
            [1,2,3,4],
            [5,6,7,8]
        ],
        [
            [1,2,3,4],
            [5,6,7,8]
        ]
    ]
])
print(tensor_four_d)

tf.Tensor(
[[[[1 2 3 4]
   [5 6 7 8]]

  [[1 2 3 4]
   [5 6 7 8]]]], shape=(1, 2, 2, 4), dtype=int32)


In [21]:
import numpy as np

In [22]:
np_array= np.array([1,2,3])
print(np_array)

[1 2 3]


In [23]:
converted_tensor=tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int64)


In [24]:
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=3,
    batch_shape=[2],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]

 [[1. 0. 0.]
  [0. 1. 0.]
  [0. 0. 1.]]], shape=(2, 3, 3), dtype=float32)


In [25]:
fill_tensor=tf.fill(
    [2,3],
    9
)
print(fill_tensor)

tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)


In [26]:
ones_tensor=tf.ones(
    [2,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [27]:
ones_like_tensor=tf.ones_like(
    eye_tensor
)
print(ones_like_tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 3, 3), dtype=float32)


In [28]:
zeros_tensor=tf.zeros(
    [2,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(zeros_tensor)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [29]:
zeros_like_tensor=tf.zeros_like(
    eye_tensor
)
print(zeros_like_tensor)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 3, 3), dtype=float32)


In [30]:
print(tensor_three_d.shape)

(2, 2, 3)


In [31]:
tf.rank(tensor_three_d)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [32]:
tf.size(tensor_three_d)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [33]:
tf.size(tensor_three_d,out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=12.0>

In [36]:
random_tensor= tf.random.normal(
    [3,2],
    mean=100.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 99.180695 100.47317 ]
 [ 99.61262   99.694046]
 [100.90184   99.672356]], shape=(3, 2), dtype=float32)


In [40]:
uniform_tensor= tf.random.uniform(
    [3,2],
    minval=0,
    maxval=None,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(uniform_tensor)

tf.Tensor(
[[0.2346083  0.0907079 ]
 [0.5718461  0.58348167]
 [0.24136603 0.8364717 ]], shape=(3, 2), dtype=float32)


In [41]:
tf.random.set_seed(5)
print(tf.random.uniform([1],seed=1))
print(tf.random.uniform([1],seed=1))
print(tf.random.uniform([1],seed=1))

tf.Tensor([0.3875184], shape=(1,), dtype=float32)
tf.Tensor([0.98592305], shape=(1,), dtype=float32)
tf.Tensor([0.9647], shape=(1,), dtype=float32)
